version: 0.0.{build}
image: 
- Visual Studio 2019
- ubuntu
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  COVERALLS_REPO_TOKEN:
    secure: /6Ynh8LMsDKryTdOsEc2zl0ePsN3ce+oYemlM6CFK3ChePYSavZmgIH1ENWE0ZDh
  COVERITY_TOKEN:
    secure: eJdOjCT+V5sq+EWTsuBwx8r47EHFutwOxnA2+yhdA2E=
  COVERITY_EMAIL:
    secure: YNNLrvdTPJBtXcWskGnutoOOXbWeulhguf0c7iX9Gis=
cache:
- C:\ProgramData\chocolatey\bin -> build.environment.ps1
- C:\ProgramData\chocolatey\lib -> build.environment.ps1
install:
- cmd: powershell .\build.environment.ps1
- cmd: psake appveyor-install
build_script:
- ps: Write-Host "APPVEYOR=$env:APPVEYOR"
- cmd: psake appveyor-build
- sh: dotnet build -c Release
test_script:
- cmd: psake appveyor-test
- sh: dotnet test src/csmacnz.Coveralls.Tests/csmacnz.Coveralls.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=../../
- sh: "[[ ! -z \"${COVERALLS_REPO_TOKEN}\" ]] && dotnet run -c Release --project src/csmacnz.Coveralls/csmacnz.Coveralls.csproj -- --opencover -i 'coverage.xml' --treatUploadErrorsAsWarnings --useRelativePaths || echo 'skipping coverage'"
artifacts:
- path: TestResults/Coverage.xml
  name: Coverage.xml
- path: Package/coveralls.net.*.zip
- path: Package/coveralls.net.*.nupkg
deploy:
- provider: GitHub
  release: $(GitVersion_SemVer)
  auth_token:
    secure: JLsZCRammlQx2C31swz8d888SUs8nWY7fDeyqaL0oTKkn+hXM0TeOElswwGxP2Ss
  artifact: /.*\.nupkg/,/.*\.zip/
  prerelease: true
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
    CI_WINDOWS: true
- provider: NuGet
  api_key:
    secure: 2ShBuyKkd5yraipTRuPBXK/LSUNxsqY+AysueCM+cS4Ajdqvye/ZUkH9EsZLMjjw
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
    CI_WINDOWS: true
